-- MySQL Script generated by MySQL Workbench
-- Tue Dec 22 17:32:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klienci` (
  `Klient_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Pesel` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`Klient_ID`),
  UNIQUE INDEX `Klient_ID_UNIQUE` (`Klient_ID` ASC) VISIBLE,
  UNIQUE INDEX `Pesel_UNIQUE` (`Pesel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zlecenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zlecenia` (
  `Zlecenia_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Klienci_Klient_ID` INT UNSIGNED NOT NULL,
  `Kwota` DOUBLE UNSIGNED NOT NULL,
  `Data_wyk` DATE NOT NULL,
  `Status` TINYINT(1) ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`Zlecenia_ID`, `Klienci_Klient_ID`),
  UNIQUE INDEX `Zlecenia_ID_UNIQUE` (`Zlecenia_ID` ASC) VISIBLE,
  INDEX `fk_Zlecenia_Klienci_idx` (`Klienci_Klient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Zlecenia_Klienci`
    FOREIGN KEY (`Klienci_Klient_ID`)
    REFERENCES `mydb`.`Klienci` (`Klient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rachunki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rachunki` (
  `Rachunki_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Kwota` DOUBLE UNSIGNED NOT NULL,
  `Cel` VARCHAR(45) NOT NULL,
  `Konto_bank` INT(26) UNSIGNED NOT NULL,
  `Nazwa_firmy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rachunki_ID`),
  UNIQUE INDEX `Rachunki_ID_UNIQUE` (`Rachunki_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownicy` (
  `Pracownicy_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Pesel` INT(11) UNSIGNED NOT NULL,
  `Stanowisko` VARCHAR(45) NOT NULL,
  `Nr_karty_dos` INT(9) UNSIGNED NULL,
  `zarobki` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`Pracownicy_ID`),
  UNIQUE INDEX `Pracownicy_id_UNIQUE` (`Pracownicy_ID` ASC) VISIBLE,
  UNIQUE INDEX `Pesel_UNIQUE` (`Pesel` ASC) VISIBLE,
  UNIQUE INDEX `Nr_karty_dos_UNIQUE` (`Nr_karty_dos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Platnosci` (
  `Platnosci_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Klienci_Klient_ID` INT UNSIGNED NOT NULL,
  `Konto_bank_firma` INT(26) UNSIGNED NOT NULL,
  `Kwota` DOUBLE UNSIGNED NOT NULL,
  `Status` TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`Platnosci_ID`, `Klienci_Klient_ID`),
  UNIQUE INDEX `Platnosci_ID_UNIQUE` (`Platnosci_ID` ASC) VISIBLE,
  INDEX `fk_Płatności_Klienci1_idx` (`Klienci_Klient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Płatności_Klienci1`
    FOREIGN KEY (`Klienci_Klient_ID`)
    REFERENCES `mydb`.`Klienci` (`Klient_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Magazyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Magazyn` (
  `Magazyn_ID` INT NOT NULL,
  `Nazwa` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Ilosc` INT ZEROFILL NULL,
  PRIMARY KEY (`Magazyn_ID`),
  UNIQUE INDEX `Magazyn_ID_UNIQUE` (`Magazyn_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kadra_Pracownikow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kadra_Pracownikow` (
  `Menadzer` INT UNSIGNED NOT NULL,
  `Podwladny` INT UNSIGNED NOT NULL,
  INDEX `fk_Kadra_Pracownikow_Pracownicy1_idx` (`Menadzer` ASC) VISIBLE,
  PRIMARY KEY (`Menadzer`, `Podwladny`),
  INDEX `fk_Kadra_Pracownikow_Pracownicy2_idx` (`Podwladny` ASC) VISIBLE,
  CONSTRAINT `fk_Kadra_Pracownikow_Pracownicy1`
    FOREIGN KEY (`Menadzer`)
    REFERENCES `mydb`.`Pracownicy` (`Pracownicy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kadra_Pracownikow_Pracownicy2`
    FOREIGN KEY (`Podwladny`)
    REFERENCES `mydb`.`Pracownicy` (`Pracownicy_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Klienci_BEFORE_UPDATE` BEFORE UPDATE ON `Klienci` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
